import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");

describe("homepage Recent Trades carousel", () => {
  it("uses the ten newest completed trades and preserves complete exchanged-item data", async () => {
    const [homeSource, routerSource, carouselSource, recentlyAddedSource, categoryBarSource, databaseSource] = await Promise.all([
      readFile(path.join(root, "client/src/pages/Home.tsx"), "utf8"),
      readFile(path.join(root, "server/routers.ts"), "utf8"),
      readFile(path.join(root, "client/src/components/RecentTradesCarousel.tsx"), "utf8"),
      readFile(path.join(root, "client/src/components/RecentlyAddedCarousel.tsx"), "utf8"),
      readFile(path.join(root, "client/src/components/CategoryBar.tsx"), "utf8"),
      readFile(path.join(root, "server/db.ts"), "utf8"),
    ]);
    expect(homeSource).toContain('getCompletedTrades.useQuery({ limit: 10, offset: 0, sortBy: "recent" }');
    expect(homeSource).toContain("<RecentTradesCarousel");
    expect(homeSource).toContain("<RecentlyAddedCarousel");
    expect(homeSource).not.toContain("{marketplaceQuery.isLoading ? (");
    expect(homeSource).toContain("isLoading={recentTradesQuery.isLoading}");
    expect(homeSource).toContain('<div className="min-w-0 bg-[#f4f1ea] md:col-start-2">');
    expect(routerSource).toContain("Return every offered item for each completed exchange");
    expect(routerSource).not.toContain("WHERE tpi.proposalId = ${trade.id}\n            LIMIT 4");
    expect(homeSource).toContain('className="bg-[#f4f1ea] py-0"');
    expect(homeSource).toContain('md:grid-cols-[230px_minmax(0,1fr)]');
    expect(homeSource).toContain('md:row-span-3');
    expect(homeSource).toContain('from-[#080c28] via-[#21104d] to-[#3b1d78]');
    expect(homeSource).toContain('className="min-w-0 bg-[#f4f1ea] py-3 md:col-start-2 md:row-start-1"');
    expect(homeSource).toContain('text-center font-serif text-[2.45rem]');
    expect(carouselSource).toContain('text-center font-serif text-[2.45rem] font-medium tracking-[-0.035em] text-black sm:text-[2.8rem]');
    expect(homeSource).toContain('className="container relative flex h-[400px] items-center justify-center py-0"');
    expect(homeSource).toContain('className="flex w-full max-w-6xl -translate-x-[6.5%] items-center justify-center px-4"');
    expect(homeSource).toContain('className="h-auto w-full max-w-6xl object-contain"');
    expect(homeSource).toContain("<CategoryBar />");
    expect(homeSource).toContain('from-[#11183f] via-[#4b1db7] to-[#761df2]');
    expect(homeSource).toContain('className="h-8 w-8"');
    expect(categoryBarSource).toContain('bg-[#0b102d]');
    expect(categoryBarSource).toContain('House');
    expect(categoryBarSource).toContain('Explore All');
    expect(categoryBarSource).toContain('gap-1 border-r border-white/10');
    expect(categoryBarSource).toContain('bg-[#3b267c]');
    expect(recentlyAddedSource).toContain("w-[220px]");
    expect(recentlyAddedSource).toContain("gap-4 animate-scroll");
    expect(recentlyAddedSource).toContain("aspect-[0.75]");
    expect(recentlyAddedSource).toContain("bg-transparent relative group/img");
    expect(recentlyAddedSource).toContain("rounded-xl");
    expect(recentlyAddedSource).toContain("border border-slate-200");
    expect(recentlyAddedSource).not.toContain("border-4 border-[#3974bb]");
    expect(homeSource).toContain("customGradingCompany: listing.customGradingCompany");
    expect(homeSource).toContain("conditionLabel: listing.conditionLabel");
    expect(recentlyAddedSource).toContain("customGradingCompany?: string | null");
    expect(recentlyAddedSource).toContain("conditionLabel?: string | null");
    expect(recentlyAddedSource).toContain("getGradeOrConditionPresentation");
    expect(recentlyAddedSource).toContain('declaredCompany.toLowerCase() === "other"');
    expect(recentlyAddedSource).toContain("item.customGradingCompany?.trim() || declaredCompany");
    expect(recentlyAddedSource).toContain('const condition = item.conditionLabel?.trim() || "Ungraded";');
    expect(recentlyAddedSource).toContain("text: condition");
    expect(recentlyAddedSource).not.toContain("Condition: ${item.conditionLabel");
    expect(databaseSource).toContain("customGradingCompany: getCustomGradingCompany(row.itemDetails)");
    expect(carouselSource).toContain("border-4 border-[#3974bb]");
    expect(carouselSource).toContain("ROTATION_INTERVAL_MS = 5_000");
    expect(carouselSource).toContain("window.setInterval");
    expect(carouselSource).toContain("requestAnimationFrame");
    expect(carouselSource).toContain("prefers-reduced-motion: reduce");
    expect(carouselSource).toContain("buildTradeShowcaseExchange");
    expect(carouselSource).toContain("getMemberName");
    expect(carouselSource).toContain("ticket-card");
    expect(carouselSource).toContain("border-dashed");
    expect(carouselSource).toContain("TicketDivider");
    expect(carouselSource).toContain("absolute inset-0 h-full w-full scale-125 object-cover opacity-70 blur-md");
    expect(carouselSource).toContain("relative z-10 h-full w-full object-fill");
    expect(carouselSource).toContain("h-40 w-24");
    expect(carouselSource).toContain("sm:h-44 sm:w-28");
    expect(carouselSource).toContain("bg-[#f8fafc]");
    expect(carouselSource).toContain("bg-[#dce8f7]");
    expect(carouselSource).toContain("formatEstimatedValue");
    expect(carouselSource).toContain("getGradePresentation");
    expect(carouselSource).toContain("getCategoryBadgeClass");
    expect(carouselSource).toContain("item.certificationCompany?.trim()");
    expect(carouselSource).toContain('company: item.certificationCompany?.trim() || "Graded"');
    expect(carouselSource).toContain("inline-flex items-center rounded-md px-2 py-0.5 text-sm font-extrabold ring-1");
    expect(carouselSource).toContain("Condition: ${condition.replaceAll");
    expect(carouselSource).toContain("text-[2.45rem]");
    expect(carouselSource).toContain('<TradeMember member={exchange.left.member} />');
    expect(carouselSource).toContain("<TradeMember member={exchange.right.member} />");
    expect(carouselSource).toContain("flex w-full min-w-0 flex-col items-center text-left");
    expect(carouselSource).toContain("flex w-fit max-w-full min-w-0 items-center justify-center gap-3 text-left");
    expect(carouselSource).toContain('className="mt-1 inline-flex items-center gap-1 text-base font-semibold');
    expect(carouselSource).toContain("mt-2 w-fit max-w-full space-y-1.5 text-left");
    expect(carouselSource).toContain("return member.displayName?.trim() || member.username?.trim() || \"Member\";");
    expect(carouselSource).toContain("ArrowLeft");
    expect(carouselSource).toContain("ArrowRight");
    expect(carouselSource).toContain("const DirectionIcon = side === \"left\" ? ArrowRight : ArrowLeft;");
    expect(carouselSource).toContain("Item moves toward the right member");
    expect(carouselSource).toContain("Item moves toward the left member");
    expect(carouselSource).toContain('/manus-storage/trade-quality-seal-transparent_fdff2d58.png');
    expect(carouselSource).toContain('alt="Trade Quality seal"');
    expect(carouselSource).toContain('className="h-44 w-48 object-contain');
    expect(carouselSource).not.toContain('<svg viewBox="0 0 240 220"');
    expect(carouselSource).not.toContain("textPath");
    expect(carouselSource).toContain("bg-transparent");
    expect(carouselSource).toContain('className="h-40 w-24');
    expect(carouselSource).toContain('sm:h-44 sm:w-28');
    expect(carouselSource).not.toContain("mix-blend-multiply");
    expect(carouselSource).not.toContain("trade-complete-stamp-transparent_9ec4b748.png");
    expect(carouselSource).toContain("ticket-card");
    const indexCss = await readFile(path.join(root, "client/src/index.css"), "utf8");
    const ticketCss = indexCss.slice(indexCss.indexOf("  .ticket-card {"));
    expect(ticketCss).not.toContain("radial-gradient");
    expect(ticketCss).not.toContain("ticket-card::before");
    expect(ticketCss).not.toContain("ticket-card::after");
    expect(ticketCss).not.toContain("M1 1 L29 9 L1 17 Z");
    expect(ticketCss).not.toContain("M29 1 L1 9 L29 17 Z");
    expect(carouselSource).toContain("border-4 border-[#3974bb]");
    expect(carouselSource).toContain("flex w-fit max-w-full min-w-0 items-center justify-center gap-3 text-left");
    expect(carouselSource).toContain('className="mt-1 inline-flex items-center gap-1 text-base font-semibold');
    expect(carouselSource).toContain("mt-2 w-fit max-w-full space-y-1.5 text-left");
    expect(carouselSource).toContain("text-base text-slate-700");
    expect(carouselSource).toContain("verificationLabels");
    expect(carouselSource).toContain("averageRating");
    expect(carouselSource).not.toContain('title="You gave"');
    expect(carouselSource).not.toContain('title="You received"');
    expect(carouselSource).toContain("Trade ID:");
    expect(carouselSource).toContain("Total Trade Value:");
    expect(carouselSource).toContain("Verified trade");
    expect(carouselSource).toContain("formatTradeDate");
    expect(carouselSource).toContain("text-[#315ea7]");
    expect(routerSource).toContain("l.condition as requestedListingCondition");
    expect(routerSource).toContain("l.grade as requestedListingGrade");
    expect(routerSource).toContain("l.certificationCompany as requestedListingCertificationCompany");
    expect(routerSource).toContain("req_u.username as requesterUsername");
    expect(routerSource).toContain("rec_u.username as recipientUsername");
    expect(routerSource).toContain("AVG(overallRating)");
    expect(routerSource).toContain("requesterEbayVerified");
    expect(routerSource).toContain("requesterMerchantVerified");
    expect(routerSource).toContain("ol.condition, ol.grade, ol.certificationCompany, ol.estimatedValue");
    expect(carouselSource).not.toContain("Tradebilia exchange activity");
    expect(carouselSource).not.toContain("Completed trade");
    expect(carouselSource).not.toContain("Previous recent trade");
    expect(carouselSource).not.toContain("Next recent trade");
  });
});
