import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const projectRoot = path.resolve(import.meta.dirname, "..");
const warRoomSource = fs.readFileSync(path.join(projectRoot, "client/src/pages/WarRoom.tsx"), "utf8");
const recentTradesSource = fs.readFileSync(path.join(projectRoot, "client/src/components/RecentTradesCarousel.tsx"), "utf8");
const stylesheet = fs.readFileSync(path.join(projectRoot, "client/src/index.css"), "utf8");

describe("Trade Room responsive completed-trade layout", () => {
  it("keeps receipt and trade-issue actions in a separate full-width flow section before tracking", () => {
    expect(warRoomSource).toContain('aria-label="Trade documents and support actions"');
    expect(warRoomSource).toContain('flex w-full flex-wrap items-center justify-center gap-2 rounded-xl');
    expect(warRoomSource).toContain('relative z-0 w-full flex-none bg-[#16213e]');
    expect(warRoomSource).toContain('Document a concern or add supporting details. This does not pause the trade.');
    expect(warRoomSource).toContain('Pause this trade and ask Tradebilia to review it. Your partner will be notified.');
    expect(warRoomSource).toContain('TooltipTrigger asChild');
  });

  it("stacks actions and tracking details before narrow or zoomed desktop widths can overlap", () => {
    expect(warRoomSource).toContain('w-full items-center justify-center gap-2 rounded-lg border border-blue-500/40');
    expect(warRoomSource).toContain('w-full items-center justify-center gap-2 rounded-lg border border-amber-400/35');
    expect(warRoomSource).toContain('grid grid-cols-1 gap-4 mb-4 lg:grid-cols-2');
    expect(warRoomSource).toContain('{allItems.length > 0 && <div className="grid grid-cols-1 gap-4 mb-4 lg:grid-cols-2">');
    expect(warRoomSource).toContain('flex flex-col gap-3 sm:flex-row');
  });

  it("keeps participant names and side labels readable and uses the requested inventory modal surface treatments", () => {
    expect(warRoomSource).toContain('text-base font-extrabold leading-tight">{myDisplayName}</p>');
    expect(warRoomSource).toContain('text-base font-extrabold leading-tight">{theirDisplayName}</p>');
    expect(warRoomSource).toContain('size="large" className="scale-75 origin-left"');
    expect(warRoomSource).toContain('text-blue-200 text-xs font-bold uppercase tracking-wider">Your Side</p>');
    expect(warRoomSource).toContain('text-blue-200 text-xs font-bold uppercase tracking-wider">Their Side</p>');
    expect(warRoomSource).toContain('border-gray-700 flex-shrink-0 bg-[#16213e]');
    expect(warRoomSource).toContain('bg-white text-slate-900 border border-slate-300');
    expect(warRoomSource).toContain('border-red-200 bg-red-50 text-red-700');
    expect(warRoomSource).toContain('existingTheirTradeItemIds');
    expect(warRoomSource).toContain('existingMyTradeItemIds');
    expect(warRoomSource).toContain('bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-bold');
    expect(warRoomSource).toContain('border-2 border-white/80 rounded-xl w-11/12 max-w-6xl');
    expect(warRoomSource).toContain('const myReviewHasSingleItem = myItems.length === 1;');
    expect(warRoomSource).toContain('const theirReviewHasSingleItem = theirItems.length === 1;');
    expect(warRoomSource).toContain("currentStage === 'accepted' ? 'trade-room-finalize-whole' : currentStage === 'shipping' ? 'trade-room-shipping-whole' : currentStage === 'shipped' ? 'trade-room-confirm-whole' : currentStage === 'review' ? 'trade-room-review-whole' : ''");
    expect(warRoomSource).toContain("${currentStage === 'shipped' ? 'w-16 h-16' : myReviewHasSingleItem ? 'w-full h-72' : 'w-28 h-28'}");
    expect(warRoomSource).toContain("${currentStage === 'shipped' ? 'w-16 h-16' : theirReviewHasSingleItem ? 'w-full h-72' : 'w-28 h-28'}");
    expect(warRoomSource).toContain("currentStage === 'shipped' ? 'items-center p-2'");
    expect(warRoomSource).toContain("currentStage === 'shipped' ? 'flex flex-1 min-w-0 items-center gap-3'");
    expect(warRoomSource).toContain("currentStage === 'shipped' ? 'text-base'");
    expect(warRoomSource).toContain('text-white font-bold text-2xl">Shipping Information</h2>');
    expect(warRoomSource).toContain('className="space-y-3 text-base"');
    expect(warRoomSource).toContain('bg-[#0f0f1a] border border-white/40 rounded-xl p-6');
    expect(warRoomSource).toContain('formatTradeRoomPhone(contact.contactPhone)');
    expect(warRoomSource).toContain("if (digits.length === 10) return `${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}`;");
    expect(warRoomSource).toContain('formatTimelineDetails(event, cfg.label)');
    expect(warRoomSource).toContain('Submitted shipment tracking information');
    expect(warRoomSource).toContain('Shipment Tracking Submitted');
    expect(warRoomSource).toContain('Selected ${method} as payment method');
    expect(warRoomSource).toContain('my-auto h-12 w-12 text-cyan-300');
    expect(warRoomSource).toContain("${currentStage === 'shipped' ? 'text-base' : myReviewHasSingleItem ? 'text-xl' : 'text-base'}");
    expect(warRoomSource).toContain("${currentStage === 'shipped' ? 'text-base' : theirReviewHasSingleItem ? 'text-xl' : 'text-sm'}");
    expect(warRoomSource).toContain('ml-auto shrink-0 text-right text-gray-200 text-base font-mono');
    expect(warRoomSource).toContain('w-full min-h-[38rem]');
    expect(warRoomSource).toContain('data-testid="shipping-counterparty-locked-items"');
    expect(warRoomSource).toContain('Cash payment & shipping tasks');
    expect(warRoomSource).toContain('The member sending cash must complete the payment and mark it sent.');
    expect(warRoomSource).toContain('uppercase tracking-wide animate-pulse');
    expect(warRoomSource).toContain('bg-white border border-slate-300 text-slate-900');
    expect(warRoomSource).toContain('Tracking Numbers not submitted');
    expect(warRoomSource).toContain('Valid Tracking Number has been submitted');
    expect(warRoomSource).toContain('Press Enter to lock every tracking number before submitting.');
    expect(warRoomSource).toContain('>Enter</button>');
    expect(warRoomSource).toContain('>Reset</button>');
    expect(warRoomSource).toContain('myShippingItems.length > 0 && (myTracking.length === 0 || resetTrackingIds.length > 0)');
    expect(warRoomSource).toContain("case 'completed': return reviewCount >= 2 ? 'completed' : 'review'");
    expect(warRoomSource).toContain("const visibleStages = currentStage === 'disputed' ? [...stages, { key: 'disputed' as const, label: 'Disputed', sub: 'Under Review' }] : stages;");
    expect(warRoomSource).toContain("getTrackingItemTitle = (tracking: any) => tracking.itemTitle || tradeItemTitleById.get(Number(tracking.listingId)) || 'Trade item'");
    expect(warRoomSource).toContain('lg:flex-row lg:items-stretch');
    expect(warRoomSource).toContain('trade-room-exchange-arrow my-auto h-12 w-12 text-cyan-300');
    expect(recentTradesSource).toContain('home-trade-direction-icon h-6 w-6');
    expect(stylesheet).toContain('@media (max-width: 767px)');
    expect(stylesheet).toContain('.trade-room-exchange-arrow');
    expect(stylesheet).toContain('.home-trade-direction-icon');
    expect(stylesheet).toContain('transform: rotate(90deg);');
    expect(warRoomSource).toContain('text-gray-200 text-base font-mono font-semibold flex-1 break-all');
    expect(warRoomSource).toContain('text-white text-lg font-semibold');
    expect(warRoomSource).toContain('const hasAllReviewRatings = Object.values(reviewRatings).every((rating) => rating > 0);');
    expect(warRoomSource).toContain("hasAllReviewRatings ? 'bg-yellow-600 hover:bg-yellow-700 text-white' : 'border border-slate-500 bg-slate-700 text-slate-300 hover:bg-slate-600'");
    expect(warRoomSource).toContain('<header className="relative border-b border-gray-600 bg-[#16213e] px-4 py-3 lg:px-6">');
    expect(warRoomSource).toContain('xl:absolute xl:right-[68px] xl:top-1/2 xl:z-10 xl:-translate-y-1/2');
    expect(warRoomSource).not.toContain('xl:translate-x-[82px]');
  });

  it("uses a fixed-height rail only on wide desktops and otherwise lets the entire workspace scroll naturally", () => {
    expect(warRoomSource).toContain('trade-room-shell flex min-h-[100dvh] flex-col overflow-x-hidden bg-[#0f0f1a]');
    expect(warRoomSource).toContain('trade-room-workspace flex min-h-0 flex-1 flex-col overflow-visible');
    expect(warRoomSource).toContain('trade-room-content flex flex-1 flex-col overflow-visible p-4 custom-scrollbar');
    expect(warRoomSource).toContain('trade-room-chat-rail flex min-h-[34rem] w-full flex-shrink-0 flex-col p-4');
    expect(stylesheet).toContain('@media (min-width: 1280px) and (min-height: 760px)');
    expect(stylesheet).toContain('.trade-room-shell.trade-room-finalize-whole');
    expect(stylesheet).toContain('.trade-room-shell.trade-room-shipping-whole');
    expect(stylesheet).toContain('.trade-room-shell.trade-room-confirm-whole');
    expect(stylesheet).toContain('.trade-room-shell.trade-room-review-whole');
    expect(stylesheet).toContain('transform: scale(0.67);');
    expect(stylesheet).toContain('transform-origin: top left;');
    expect(stylesheet).toContain('position: fixed;');
    expect(stylesheet).toContain('inset: 0;');
    expect(stylesheet).toContain('width: calc(100vw / 0.67);');
    expect(stylesheet).toContain('height: calc(100dvh / 0.67);');
    expect(stylesheet).toContain('min-height: calc(100dvh / 0.67);');
    expect(stylesheet).not.toContain('margin-bottom: calc((100dvh - 6rem) * -0.4925);');
    expect(stylesheet).toContain('html:has(.trade-room-shell.trade-room-finalize-whole)');
    expect(stylesheet).toContain('html:has(.trade-room-shell.trade-room-shipping-whole)');
    expect(stylesheet).toContain('html:has(.trade-room-shell.trade-room-confirm-whole)');
    expect(stylesheet).toContain('html:has(.trade-room-shell.trade-room-review-whole)');
    expect(stylesheet).toContain('body:has(.trade-room-shell.trade-room-finalize-whole)');
    expect(stylesheet).toContain('overflow: hidden;');
    expect(stylesheet).toContain('background: #0f0f1a;');
    expect(stylesheet).toContain('.trade-room-chat-rail');
    expect(stylesheet).toContain('width: 440px;');
    expect(stylesheet).toContain('height: 100%;');
    expect(warRoomSource).toContain('px-3 py-3 sm:px-6 sm:py-4');
  });
});
